apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  hostNetwork: true
  hostIPC: true
  hostPID: true
  securityContext:
    runAsUser: 1000
  containers:
  - image: busybox
    name: busybox
    command: ["sleep", "500"]
    securityContext:
      readOnlyRootFilesystem: true
  restartPolicy: Always
